"""Report generation module for creating formatted reports"""

import os
from datetime import datetime
from typing import Dict
from src.utils.config import Config


class ReportGenerator:
    """Generates formatted reports from synthesized research"""
    
    def generate_markdown_report(self, topic: str, synthesis_data: Dict, research_results: List[Dict]) -> str:
        """
        Generate a markdown-formatted report
        
        Args:
            topic: Research topic
            synthesis_data: Synthesized data from Synthesizer
            research_results: Original research results
            
        Returns:
            Markdown-formatted report string
        """
        report = []
        
        # Header
        report.append(f"# Research Report: {topic}\n")
        report.append(f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        report.append(f"**Sources Analyzed:** {synthesis_data.get('num_sources', 0)}\n")
        report.append("\n---\n\n")
        
        # Executive Summary
        report.append("## Executive Summary\n")
        synthesis = synthesis_data.get('synthesis', '')

        if isinstance(synthesis, list):
            synthesis = "\n\n".join(str(s) for s in synthesis)

        # Extract first paragraph as summary
        summary = synthesis.split('\n\n')[0] if synthesis else "No summary available."
        report.append(f"{summary}\n\n")
        
        # Main Synthesis
        report.append("## Detailed Analysis\n")
        report.append(f"{synthesis}\n\n")
        
        # Sources
        report.append("## Sources\n")
        sources = synthesis_data.get('sources', [])
        for i, source in enumerate(sources, 1):
            title = source.get('title', 'Untitled')
            url = source.get('url', '#')
            report.append(f"{i}. [{title}]({url})\n")
        
        report.append("\n---\n\n")
        report.append(f"*Report generated by Intelligent Research Agent*\n")
        
        return "\n".join(report)
    
    def save_report(self, report_content: str, topic: str, format: str = "markdown") -> str:
        """
        Save report to file
        
        Args:
            report_content: Report content string
            topic: Research topic (used for filename)
            format: Report format (markdown, html, etc.)
            
        Returns:
            Path to saved file
        """
        # Create safe filename from topic
        safe_topic = "".join(c for c in topic if c.isalnum() or c in (' ', '-', '_')).rstrip()
        safe_topic = safe_topic.replace(' ', '_')[:50]  # Limit length
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"{safe_topic}_{timestamp}.{format}"
        filepath = Config.get_output_path(filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        return filepath
    
    def generate_html_report(self, markdown_content: str) -> str:
        """Convert markdown report to HTML"""
        try:
            import markdown
            html = markdown.markdown(markdown_content, extensions=['extra', 'codehilite'])
            
            # Wrap in HTML template
            html_template = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Research Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        code {{ background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        pre {{ background-color: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }}
    </style>
</head>
<body>
{html}
</body>
</html>"""
            return html_template
        except ImportError:
            print("Warning: markdown library not available. Returning markdown as-is.")
            return markdown_content
