"""
Report generation module — consumes a typed SynthesizerOutput and produces
clean, well-structured markdown with a full Citation Index.
"""

import os
from datetime import datetime
from typing import Optional

from src.models.outputs import SynthesizerOutput, EvaluationScore
from src.utils.config import Config


class ReportGenerator:
    """Generates formatted markdown (and optionally HTML) reports."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_markdown_report(
        self,
        synthesis: SynthesizerOutput,
        score: Optional[EvaluationScore] = None,
    ) -> str:
        """
        Build a complete markdown report from a SynthesizerOutput.

        Args:
            synthesis: Validated SynthesizerOutput from Synthesizer.
            score:     Optional quality score from EvaluationScorer (Phase 4).

        Returns:
            Markdown string ready to display or save.
        """
        parts: list[str] = []

        # ── Header ──────────────────────────────────────────────────────
        parts.append(f"# Research Report: {synthesis.topic}\n")
        parts.append(
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n"
            f"**Sources Analysed:** {len(synthesis.source_quotes) or 'N/A'}  \n"
            f"**Depth Confidence:** {synthesis.overall_confidence:.0%}  \n"
        )
        if score:
            parts.append(
                f"**Quality Score:** {score.overall:.0%}  "
                f"(Coverage {score.source_coverage:.0%} · "
                f"Citations {score.citation_accuracy:.0%} · "
                f"Coherence {score.synthesis_coherence:.0%})\n"
            )
        parts.append("\n---\n")

        # ── Executive Summary ────────────────────────────────────────────
        parts.append("## Executive Summary\n")
        parts.append(f"{synthesis.executive_summary}\n")

        # ── Key Statistics ───────────────────────────────────────────────
        if synthesis.key_statistics:
            parts.append("\n## Key Statistics\n")
            for stat in synthesis.key_statistics:
                parts.append(f"- {stat}\n")

        # ── Detailed Sections ────────────────────────────────────────────
        parts.append("\n## Detailed Analysis\n")
        for section in synthesis.sections:
            parts.append(f"\n### {section.heading}\n")
            parts.append(f"{section.content}\n")

        # ── Gaps & Limitations ───────────────────────────────────────────
        if synthesis.gaps_identified:
            parts.append("\n## Gaps & Limitations\n")
            for gap in synthesis.gaps_identified:
                parts.append(f"- {gap}\n")

        # ── Citation Index ───────────────────────────────────────────────
        # Only rendered if the LLM actually populated source_quotes
        if synthesis.source_quotes:
            parts.append("\n## Citation Index\n")
            parts.append(
                "_Every [n] marker in the analysis above traces back to a source below._\n"
            )
            seen: set[int] = set()
            for q in sorted(synthesis.source_quotes, key=lambda x: x.source_index):
                if q.source_index in seen:
                    continue
                seen.add(q.source_index)
                parts.append(
                    f"\n**[{q.source_index}]** [{q.title}]({q.url})  \n"
                    f"> *\"{q.exact_quote}\"*\n"
                )

        # ── Sources ──────────────────────────────────────────────────────
        parts.append("\n## Sources\n")
        seen_urls: set[str] = set()
        idx = 1
        for q in sorted(synthesis.source_quotes, key=lambda x: x.source_index):
            if q.url in seen_urls:
                continue
            seen_urls.add(q.url)
            parts.append(f"{idx}. [{q.title}]({q.url})\n")
            idx += 1

        # ── Footer ───────────────────────────────────────────────────────
        parts.append("\n---\n")
        parts.append("*Report generated by Intelligent Research Agent v2*\n")

        return "".join(parts)

    def save_report(
        self,
        report_content: str,
        topic: str,
        fmt: str = "markdown",
    ) -> str:
        """
        Save a report to the outputs/ directory.

        Args:
            report_content: Markdown (or HTML) string.
            topic:          Research topic (used for filename).
            fmt:            File extension — 'markdown' or 'html'.

        Returns:
            Absolute path to the saved file.
        """
        ext = "md" if fmt == "markdown" else fmt
        safe_topic = (
            "".join(c for c in topic if c.isalnum() or c in " -_")
            .strip()
            .replace(" ", "_")[:50]
        )
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_topic}_{timestamp}.{ext}"
        filepath = Config.get_output_path(filename)

        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(report_content)

        return filepath

    def generate_html_report(self, markdown_content: str, topic: str = "") -> str:
        """Convert a markdown report to a self-contained HTML page."""
        try:
            import markdown as md_lib
            body_html = md_lib.markdown(
                markdown_content,
                extensions=["extra", "toc", "tables"],
            )
        except ImportError:
            body_html = f"<pre>{markdown_content}</pre>"

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Research Report: {topic}</title>
  <style>
    @page {{ size: A4; margin: 2cm; }}
    body {{
      font-family: Georgia, 'Times New Roman', serif;
      font-size: 11pt;
      line-height: 1.7;
      color: #1a1a1a;
      max-width: 860px;
      margin: 2rem auto;
      padding: 0 1.5rem;
    }}
    h1 {{ color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 0.4rem; }}
    h2 {{ color: #2c5282; margin-top: 2rem; }}
    h3 {{ color: #2d3748; }}
    a {{ color: #3182ce; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    blockquote {{
      border-left: 3px solid #6366f1;
      padding-left: 1rem;
      color: #4a5568;
      font-style: italic;
      margin: 0.5rem 0;
    }}
    code {{ background: #f7f7f7; padding: 0.1em 0.35em; border-radius: 3px; font-size: 0.88em; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
    th {{ background: #edf2f7; text-align: left; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 0.5rem 0.75rem; }}
    tr:nth-child(even) td {{ background: #f8fafc; }}
    sup a {{ color: #6366f1; font-weight: 600; font-size: 0.75em; }}
  </style>
</head>
<body>
{body_html}
</body>
</html>"""
