"""
All Pydantic output models for the Research Agent pipeline.

Every LLM response and every inter-agent data transfer uses these
typed models — no raw dicts passed between components.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ResearchDepth(str, Enum):
    SHALLOW = "shallow"
    MEDIUM = "medium"
    DEEP = "deep"


class FactVerdict(str, Enum):
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    UNVERIFIABLE = "UNVERIFIABLE"


# ---------------------------------------------------------------------------
# Planner outputs
# ---------------------------------------------------------------------------

class SubTopic(BaseModel):
    """A single research sub-topic generated by the planner."""
    query: str = Field(description="The specific search query for this sub-topic")
    priority: int = Field(ge=1, le=5, description="Research priority, 1=highest")
    rationale: str = Field(description="Why this sub-topic matters for the overall research")


class PlannerOutput(BaseModel):
    """Structured output from ResearchPlanner."""
    depth: ResearchDepth = Field(description="Determined research depth")
    sub_topics: List[SubTopic] = Field(
        description="List of sub-topics to research in parallel"
    )
    estimated_sources_needed: int = Field(
        ge=1, le=50,
        description="Estimated number of sources needed for thorough coverage"
    )
    complexity_score: float = Field(
        ge=0.0, le=1.0,
        description="Topic complexity score: 0=simple, 1=very complex"
    )


# ---------------------------------------------------------------------------
# Synthesizer outputs
# ---------------------------------------------------------------------------

class SourceQuote(BaseModel):
    """A verbatim quote extracted from a source, mapped to a citation index."""
    source_index: int = Field(
        ge=1,
        description="1-based index matching the [n] citation marker in synthesis text"
    )
    url: str = Field(description="Source URL")
    title: str = Field(description="Source page title")
    exact_quote: str = Field(
        description="Verbatim text snippet from the source (max 300 chars)"
    )
    relevance_score: float = Field(
        ge=0.0, le=1.0,
        description="How relevant this quote is to the claim it supports"
    )


class SynthesisSection(BaseModel):
    """A single section of the synthesized report."""
    heading: str = Field(description="Section heading (e.g. 'Key Findings')")
    content: str = Field(
        description="Section body text. Must contain [n] citation markers for every factual claim."
    )
    citations_used: List[int] = Field(
        default_factory=list,
        description="List of source_index values cited within this section"
    )


class SynthesizerOutput(BaseModel):
    """Structured output from Synthesizer — the core research synthesis."""
    topic: str = Field(description="The original research topic")
    executive_summary: str = Field(
        description="2-3 sentence executive summary of the entire research"
    )
    sections: List[SynthesisSection] = Field(
        description="Report sections: Key Findings, Themes, Perspectives, Statistics, Gaps, Conclusion"
    )
    key_statistics: List[str] = Field(
        default_factory=list,
        description="Notable statistics or data points found, each with [n] citation"
    )
    gaps_identified: List[str] = Field(
        default_factory=list,
        description="Areas where information was limited or missing"
    )
    source_quotes: List[SourceQuote] = Field(
        default_factory=list,
        description="All verbatim quotes used as citation evidence"
    )
    overall_confidence: float = Field(
        ge=0.0, le=1.0,
        description="Overall synthesis confidence based on source quality and coverage"
    )


# ---------------------------------------------------------------------------
# Fact-checker outputs
# ---------------------------------------------------------------------------

class FactCheckResult(BaseModel):
    """Result of fact-checking a single claim."""
    claim: str = Field(description="The specific claim being verified")
    verdict: FactVerdict = Field(description="SUPPORTED, CONTRADICTED, or UNVERIFIABLE")
    supporting_sources: List[int] = Field(
        default_factory=list,
        description="source_index values that support or contradict this claim"
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence in the verdict"
    )
    evidence: Optional[str] = Field(
        default=None,
        description="Brief explanation of the evidence used for this verdict"
    )


# ---------------------------------------------------------------------------
# Critic outputs
# ---------------------------------------------------------------------------

class CriticOutput(BaseModel):
    """Output from CriticAgent — a structured peer review of the synthesis."""
    overall_quality: float = Field(
        ge=0.0, le=1.0,
        description="Overall quality score assigned by the critic"
    )
    strengths: List[str] = Field(
        default_factory=list,
        description="What the synthesis does well"
    )
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Logical gaps, unsupported claims, or shallow coverage"
    )
    suggested_improvements: List[str] = Field(
        default_factory=list,
        description="Actionable suggestions to improve the synthesis"
    )
    missing_perspectives: List[str] = Field(
        default_factory=list,
        description="Viewpoints or stakeholders not represented in the synthesis"
    )


# ---------------------------------------------------------------------------
# Evaluation score
# ---------------------------------------------------------------------------

class EvaluationScore(BaseModel):
    """Multi-dimension quality score computed by ResearchEvaluator."""
    source_coverage: float = Field(
        ge=0.0, le=1.0,
        description="Fraction of retrieved sources actually cited in synthesis (weight 25%)"
    )
    citation_accuracy: float = Field(
        ge=0.0, le=1.0,
        description="Fraction of source_quotes fuzzy-matched in raw source content (weight 30%)"
    )
    synthesis_coherence: float = Field(
        ge=0.0, le=1.0,
        description="Fraction of sections with substantive content >100 chars (weight 25%)"
    )
    factual_density: float = Field(
        ge=0.0, le=1.0,
        description="Fraction of SUPPORTED verdicts among all fact checks (weight 20%)"
    )
    overall: float = Field(
        ge=0.0, le=1.0,
        description="Weighted composite score"
    )
    breakdown: Dict[str, Any] = Field(
        default_factory=dict,
        description="Raw component values used to compute each dimension"
    )


# ---------------------------------------------------------------------------
# Top-level research result
# ---------------------------------------------------------------------------

class ResearchResult(BaseModel):
    """
    The complete output of ResearchAgent.research().
    Returned to the API layer and stored in the database.
    """
    report_id: str = Field(description="UUID assigned at persist time")
    topic: str
    depth: str

    # Pipeline outputs (all optional — set progressively as pipeline runs)
    plan: Optional[PlannerOutput] = None
    synthesis: Optional[SynthesizerOutput] = None
    fact_checks: Optional[List[FactCheckResult]] = None
    critique: Optional[CriticOutput] = None
    score: Optional[EvaluationScore] = None

    # Final deliverables
    report: str = Field(description="Final markdown report string")
    report_path: Optional[str] = Field(default=None, description="Path to saved .md file")
    pdf_path: Optional[str] = Field(default=None, description="Path to saved .pdf file")

    # Metadata
    num_sources: int = Field(default=0)
    created_at: str = Field(description="ISO-8601 timestamp")

    class Config:
        # Allow serialization of Enum values as strings
        use_enum_values = True
